### ISSUE TITLE
NetworkServerConnection and NetworkClientConnection missing overrides.

### ISSUE THREAD

**Issue by Derek-R-S** [DarkRiftNetworking/DarkRift.Documentation#3]
In the documents [here](https://github.com/DarkRiftNetworking/DarkRift.Documentation/blob/master/advanced/network_listeners.md#custom-network-listeners) the example for NetworkServerConnection and NetworkClientConnection have methods that need overrides but does not have it in the examples.

**Comment by JamJar00** [comment]
Fixed in next version!
