### ISSUE TITLE
LatestRTT and SmoOthedRtt Documentation Bug

### ISSUE THREAD

**Issue by chadfranklin47** [DarkRiftNetworking/DarkRift.Documentation#7]
![image](https://user-images.githubusercontent.com/37273511/74111936-73d04d80-4b66-11ea-91a1-8be8772cbbc9.png)
Both LatestRtt and SmothedRtt have the same description while LatestRtt should be different. Also, SmoothedRtt is spelled incorrectly as "SmothedRtt".

**Comment by JamJar00** [comment]
Nice spot, bit embarrasing aha

Fixed in the next version
